# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - master
  paths:
    include:
      - Client/*

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: YarnInstaller@3
  inputs:
    versionSpec: '1.x'
    checkLatest: true

- task: Yarn@3
  displayName: 'Install Dependencies'
  inputs:
    projectDirectory: 'Client'
    arguments: 'install'

- task: Yarn@3
  displayName: 'Run Tests'
  inputs:
    projectDirectory: 'Client'
    arguments: 'test'
  env:
    CI: true

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.BinariesDirectory)'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true
